import "@styles/globals.scss";

import Header from "@components/Header/Header"
import Footer from "@components/Footer/Footer"

export const metadata = {
  title: "Create Next Appfsdfs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        <>{children}</>
        <Footer></Footer>
      </body>
    </html>
  );
}