services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: webscavul_app
    restart: always
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ./:/webscavul
  mariadb:
    image: mariadb
    container_name: webscavul_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - data:/var/lib/mysql
      - ./db_scripts:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"

volumes:
  data: