services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: webscavul_app
    restart: always
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ./:/webscavul
  mariadb:
    image: mariadb
    container_name: webscavul_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - data:/var/lib/mysql

volumes:
  data: