services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: webscavul_api
    depends_on:
      - mariadb
    restart: always
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ./api:/webscavul/api
    networks:
      - backend
      
  app:
    build:
      context: ./webapp
      dockerfile: Dockerfile.dev
    container_name: webscavul_app
    depends_on:
      - api
    restart: always
    env_file: .env
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./webapp:/webscavul/webapp
      - /webscavul/webapp/node_modules
    networks:
      - backend

  mariadb:
    image: mariadb
    container_name: webscavul_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - data:/var/lib/mysql
      - ./db_scripts:/docker-entrypoint-initdb.d/:ro
    ports:
      - "${DB_PORT}:3306"
    networks:
      - backend

volumes:
  data:

networks:
  backend: