FROM --platform=linux/amd64 node:22-alpine AS dev

WORKDIR /webscavul/webapp

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true
ENV WATCHPACK_POLLING_INTERVAL=300

# Instala dependencias del sistema necesarias
RUN apk add --no-cache libc6-compat

# Copia solo los archivos de dependencias para cachear instalación
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./

# Instala dependencias
RUN \
  if [ -f yarn.lock ]; then yarn; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install; \
  else npm install; \
  fi

# Copia el resto del código
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]